# Generated by Django 5.2.4 on 2025-07-06 17:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of your blog post', max_length=200)),
                ('content', models.TextField(help_text='The main content of your blog post')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When the post was created')),
                ('published_date', models.DateTimeField(blank=True, help_text='When the post was published (can be empty for drafts)', null=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title', max_length=200, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Post status: draft or published', max_length=10)),
                ('excerpt', models.TextField(blank=True, help_text='Short description of the post (optional)', max_length=300)),
                ('author', models.ForeignKey(help_text='The author of this post', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_date'],
            },
        ),
    ]
